name: eye_oculus
description: Eye Oculus app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  speech_to_text: ^0.8.0
  assets_audio_player: ^1.2.3
  flutter_alert: ^0.4.0
  http: ^0.12.0+4
  web_socket_channel: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/on.mp3
    - assets/off.mp3
    - assets/dropdown1.mp3
    - assets/dropdown2.mp3
    - assets/dropdown3.mp3
    - assets/dropdown4.mp3
    - assets/dropdown5.mp3


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
